blog/urls.py
from django.urls import path
from blog.views import greeting, time, blog_view, blog_detail_view, about_view, contact_view

urlpatterns = [
    path('greeting/', greeting),
    path('time/', time),
    path('', blog_view),
    path('blog/<int:id>/', blog_detail_view),
    path('about/', about_view),
    path('contact/', contact_view),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls")),
    path('', include("services.urls")),
    path('', include("registration.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

registration/urls.py
from django.urls import path
from . import views

app_name = 'persons'

urlpatterns = [
    path('register/', views.RegistrationView.as_view()),
    path('login/', views.InLoginView.as_view(), name='login'),
    path('logout/', views.OutLogoutView.as_view(), name='logout'),
    path('person_list/', views.UserListView.as_view(), name='person_list'),

]

services/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('services_list/', views.ServiceListView.as_view()),
    path('services_list/<int:id>/delete/', views.DeleteServiceView.as_view()),
    path('services_list/<int:id>/update/', views.UpdateServiceView.as_view()),
    path('create_services/', views.CreateServiceView.as_view()),
]

blog/models.py
from django.db import models


class Slider(models.Model):
    slides = models.URLField()

    def __str__(self):
        return self.slides

    class Meta:
        verbose_name = 'слайд'
        verbose_name_plural = 'слайды'


class Motto(models.Model):
    text = models.CharField(max_length=250)
    video_url = models.URLField()

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'девиз'
        verbose_name_plural = 'девизы'


class Contact(models.Model):
    adress = models.CharField(max_length=100)
    email = models.EmailField(default="@gmail.com", blank=True)
    phone_number = models.CharField(max_length=16)
    map = models.URLField()

    def __str__(self):
        return self.adress

    class Meta:
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'


class About(models.Model):
    text = models.TextField()
    logo = models.ImageField()

    def __str__(self):
        return self.text


class BlogTable(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='')
    description = models.TextField()
    instagram = models.URLField()
    music = models.FileField(upload_to='music/', null=True)
    price = models.PositiveIntegerField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title}-{self.created_at}'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

services/models.py
from datetime import datetime
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

CHOICES_SERVICES = (
    ('Разработка веб сайтов', 'Разработка веб сайтов'),
    ('Разработка мобильных приложений', 'Разработка мобильных приложений'),
    ('Разработка DescTopApp', 'Разработка DescTopApp'),
)


class Service(models.Model):
    title = models.CharField(max_length=100, verbose_name='Напишите название услуги')
    description = models.TextField(verbose_name='Напишите описание услуги')
    choices_services = models.CharField(max_length=100, choices=CHOICES_SERVICES,
                                        verbose_name='Выберите категорию услуг')
    prepaid_expense = models.PositiveIntegerField(validators=[MinValueValidator(1000),
                                                              MaxValueValidator(3000)],
                                                  verbose_name='Внесите аванс', default=1500)
    card_number = models.CharField(max_length=16, verbose_name='Напишите номер карты')
    card_month = models.PositiveIntegerField(null=True,
                                             verbose_name='Укажите месяц', default=1)
    card_year = models.PositiveIntegerField(null=True,
                                            verbose_name='Укажите год', default=2000)
    card_cvv = models.CharField(max_length=3, verbose_name='Укажите cvv')
    email = models.EmailField(verbose_name='Укажите почту', default='@gmail.com')
    dead_line = models.DateTimeField(verbose_name='Укажите дедлайн', default=datetime.now())

    def __str__(self):
        return f'{self.title} - {self.dead_line}'


services/forms.py
from django import forms
from services.models import Service


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = "__all__"

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from datetime import datetime
from blog.models import BlogTable, About, Contact, Motto, Slider


def blog_view(request):
    if request.method == "GET":
        blog = BlogTable.objects.all()
        motto = Motto.objects.all()
        slider = Slider.objects.all()
        return render(request, template_name="news.html",
                      context={
                          'blog': blog,
                          'motto': motto,
                          'slider': slider
                      })


def blog_detail_view(request, id):
    if request.method == "GET":
        blog_id = get_object_or_404(BlogTable, id=id)
        return render(request, template_name='news_detail.html',
                      context={'blog_id': blog_id})


def about_view(request):
    if request.method == "GET":
        about = About.objects.all()
        return render(request, template_name='about.html', context={'about': about})


def contact_view(request):
    if request.method == "GET":
        contact = Contact.objects.all()
        return render(request, template_name='contact.html', context={'contact': contact})


# Greeting
def greeting(request):
    if request.method == "GET":
        return HttpResponse("<h1>Привет ребята добро пожаловать в DJANGO TEMPLATES</h1>")


# Time
def time(request):
    if request.method == "GET":
        return HttpResponse(f"<h1>На данный момент сейчас время - {datetime.now()}")

services/views.py
from django.shortcuts import get_object_or_404

from . import forms, models
from django.http import HttpResponse
from django.views import generic


class ServiceListView(generic.ListView):
    template_name = 'services.html'
    context_object_name = 'services'
    model = models.Service

    def get_queryset(self):
        return self.model.objects.all()


class CreateServiceView(generic.CreateView):
    template_name = 'create_service.html'
    form_class = forms.ServiceForm
    success_url = '/services_list/'

    def form_valid(self, form):
        print(form.cleaned_data)
        return super(CreateServiceView, self).form_valid(form=form)


class DeleteServiceView(generic.DeleteView):
    template_name = 'confirm_delete.html'
    success_url = '/services_list/'

    def get_object(self, **kwargs):
        service_id = self.kwargs.get("id")
        return get_object_or_404(models.Service, id=service_id)


class UpdateServiceView(generic.UpdateView):
    template_name = 'update_service.html'
    form_class = forms.ServiceForm
    success_url = '/services_list/'

    def get_object(self, **kwargs):
        service_id = self.kwargs.get("id")
        return get_object_or_404(models.Service, id=service_id)

    def form_valid(self, form):
        print(form.cleaned_data)
        return super(UpdateServiceView, self).form_valid(form=form)

templates/about.html
{% include 'header.html' %}

{% for i in about %}
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6">
      <h2>About Us</h2>
      <p class="lead">{{i.text}}</p>

      <!-- Contact Information -->
      <div class="mt-4">
        <h5>Contact Us</h5>
        <p>Email: info@itb23.com</p>
        <p>Phone: +1 (123) 456-7890</p>
      </div>
    </div>

    <div class="col-md-6">
      <!-- Image -->
      <img src="{{i.logo.url}}" alt="ITB23 Team" class="img-fluid rounded">
    </div>
  </div>
</div>
{% endfor %}
{% include 'footer.html' %}

templates/confirm_delete.html
{% include 'header.html' %}


<center>
    <h1>Вы уверенны что хотите удалить заказ?</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit">Удалить</button>
    </form>
</center>



<br><br><br><br><br><br><br><br><br>
{% include 'footer.html' %}

templates/contact.html
{% load static %}
{% include 'header.html' %}

{% for i in contact %}
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6">
      <h2>Contact Us</h2>

      <!-- Address -->
      <p><strong>Address:</strong> {{ i.adress }}</p>

      <!-- Email -->
      <p><strong>Email:</strong> <a href="#">{{ i.email }}</a></p>

      <!-- Phone Number -->
      <p><strong>Phone Number:</strong> {{ i.phone_number }}</p>

      <!-- Map -->

       <div id="map" style="width:500px; height:400px"></div>

              <script src="https://maps.api.2gis.ru/2.0/loader.js?pkg=full"></script>

        <script type="text/javascript" src="{% static 'js/map.js' %}"></script>


    </div>
  </div>
</div>

{% endfor %}

{% include 'footer.html' %}

templates/create_service.html
{% load static %}
{% include 'header.html' %}
<link rel="stylesheet" href="{% static 'css/create_service.css' %}">
<form class="decor" action="/create_services/" method="POST" enctype="multipart/form-data">
    <div class="form-left-decoration"></div>
    <div class="form-right-decoration"></div>
    <div class="circle"></div>
    <div class="form-inner">
        <h3>Добавить заказ</h3>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Отправить">
        <input type="reset" value="Очистить">
    </div>
</form>
{% include 'footer.html' %}

templates/footer.html

<footer class="bg-dark text-white text-center py-3">
  <p>&copy; 2024 Your Website. All rights reserved.</p>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

templates/header.html

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <title>Your Website</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Your Logo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/about/">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/create_services/">Services</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact/">Contact</a>
      </li>
    </ul>
  </div>
</nav>

templates/login.html
<form method="POST" enctype="multipart/form-data" class="transparent">
    <div class="form-inner">
        <h3>Авторизация</h3>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Авторизация">
    </div>
</form>


<style>
    * {
        box-sizing: border-box;
    }

    .transparent {
        position: relative;
        max-width: 400px;
        padding: 60px 50px;
        margin: 50px auto 0;
        background-image: url(https://html5book.ru/wp-content/uploads/2017/01/photo-roses.jpg);
        background-size: cover;
    }

    .transparent:before {
        content: "";
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: linear-gradient(to right bottom, rgba(43, 44, 78, .5), rgba(104, 22, 96, .5));
    }

    .form-inner {
        position: relative;
    }

    .form-inner h3 {
        position: relative;
        margin-top: 0;
        color: white;
        font-family: 'Roboto', sans-serif;
        font-weight: 300;
        font-size: 26px;
        text-transform: uppercase;
    }

    .form-inner h3:after {
        content: "";
        position: absolute;
        left: 0;
        bottom: -6px;
        height: 2px;
        width: 60px;
        background: #1762EE;
    }

    .form-inner label {
        display: block;
        padding-left: 15px;
        font-family: 'Roboto', sans-serif;
        color: rgba(255, 255, 255, .6);
        text-transform: uppercase;
        font-size: 14px;
    }

    .form-inner input {
        display: block;
        width: 100%;
        padding: 0 15px;
        margin: 10px 0 15px;
        border-width: 0;
        line-height: 40px;
        border-radius: 20px;
        color: white;
        background: rgba(255, 255, 255, .2);
        font-family: 'Roboto', sans-serif;
    }

    .form-inner input[type="checkbox"] {
        position: absolute;
        opacity: 0;
    }

    #custom-checkbox + label {
        position: relative;
        margin: 20px 0;
        text-transform: none;
        cursor: pointer;
    }

    #custom-checkbox + label:before {
        content: "";
        display: inline-block;
        width: 20px;
        height: 20px;
        margin-right: 10px;
        vertical-align: text-top;
        background: white;
    }

    #custom-checkbox:checked + label:before {
        background: #1762EE;
    }

    #custom-checkbox:checked + label:after {
        content: "";
        position: absolute;
        width: 2px;
        height: 2px;
        left: 20px;
        top: 9px;
        background: white;
        box-shadow: 2px 0 0 white, 4px 0 0 white, 4px -2px 0 white, 4px -4px 0 white, 4px -6px 0 white, 4px -8px 0 white;
        transform: rotate(45deg);
    }

    .form-inner input[type="submit"] {
        background: #1762EE;
    }
</style>

templates/news.html

{% include 'header.html' %}

{% for i in motto %}
 <div class="container mt-5 text-center border border-primary p-4">
    <h1 class="text-primary">{{i.text}}</h1>
  </div>
{% endfor %}

{% for i in motto %}
<div class="container mt-5 border border-primary p-4">
    <iframe class="border border-primary rounded" width="100%" height="400" src="{{i.video_url}}"></iframe>
</div>
{% endfor %}


<!--Слайдеры-->
<h2 class="mt-4 text-center">Слайды</h2>
 <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        {% for i in slider %}
        <li data-target="#myCarousel" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
        {% endfor %}
    </ol>
    <div class="carousel-inner">
        {% for i in slider %}
        <div class="carousel-item {% if forloop.first %}active{% endif %} text-center">
            <img src="{{ i.slides }}" alt="">
            <div class="carousel-caption">
                <h3></h3>
            </div>
        </div>
        {% endfor %}
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>





<div class="container mt-5">
    <div class="row">
        {% for i in blog %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <img src="{{i.image.url}}" class="card-img-top" alt="">
                <div class="card-body">
                    <h5 class="card-title">{{i.title}}</h5>
                    <p class="card-text"><small class="text-muted">Created at: {{i.created_at}}</small></p>
                    <button><a href="/blog/{{i.id}}/">Детально</a></button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% include 'footer.html' %}






templates/news_detail.html
{% include 'header.html' %}

<div class="container mt-5">
  <div class="row">
    <div class="col-md-6">
      <h2>{{blog_id.title}}</h2>
      <p>{{blog_id.description}}</p>
       <img src="{{blog_id.image.url}}" alt="Description of your image" class="img-fluid mb-3">
      <a href="{{blog_id.instagram}}" target="_blank" rel="noopener noreferrer">Instagram</a>
      <!-- Audio Player -->
      <audio controls>
        <source src="{{blog_id.music.url}}" type="audio/mp3">
        Your browser does not support the audio tag.
      </audio>
      <p>{{blog_id.price}}</p>
      <p class="text-muted mt-3">Published on: <span class="text-primary">{{blog_id.created_at}}</span></p>
    </div>
  </div>
</div>

{% include 'footer.html' %}

templates/register.html
<form method="POST" enctype="multipart/form-data" class="transparent">
    <div class="form-inner">
        <h3>Регистрация</h3>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Регистрация">
    </div>
</form>


<style>
    * {
        box-sizing: border-box;
    }

    .transparent {
        position: relative;
        max-width: 400px;
        padding: 60px 50px;
        margin: 50px auto 0;
        background-image: url(https://html5book.ru/wp-content/uploads/2017/01/photo-roses.jpg);
        background-size: cover;
    }

    .transparent:before {
        content: "";
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: linear-gradient(to right bottom, rgba(43, 44, 78, .5), rgba(104, 22, 96, .5));
    }

    .form-inner {
        position: relative;
    }

    .form-inner h3 {
        position: relative;
        margin-top: 0;
        color: white;
        font-family: 'Roboto', sans-serif;
        font-weight: 300;
        font-size: 26px;
        text-transform: uppercase;
    }

    .form-inner h3:after {
        content: "";
        position: absolute;
        left: 0;
        bottom: -6px;
        height: 2px;
        width: 60px;
        background: #1762EE;
    }

    .form-inner label {
        display: block;
        padding-left: 15px;
        font-family: 'Roboto', sans-serif;
        color: rgba(255, 255, 255, .6);
        text-transform: uppercase;
        font-size: 14px;
    }

    .form-inner input {
        display: block;
        width: 100%;
        padding: 0 15px;
        margin: 10px 0 15px;
        border-width: 0;
        line-height: 40px;
        border-radius: 20px;
        color: white;
        background: rgba(255, 255, 255, .2);
        font-family: 'Roboto', sans-serif;
    }

    .form-inner input[type="checkbox"] {
        position: absolute;
        opacity: 0;
    }

    #custom-checkbox + label {
        position: relative;
        margin: 20px 0;
        text-transform: none;
        cursor: pointer;
    }

    #custom-checkbox + label:before {
        content: "";
        display: inline-block;
        width: 20px;
        height: 20px;
        margin-right: 10px;
        vertical-align: text-top;
        background: white;
    }

    #custom-checkbox:checked + label:before {
        background: #1762EE;
    }

    #custom-checkbox:checked + label:after {
        content: "";
        position: absolute;
        width: 2px;
        height: 2px;
        left: 20px;
        top: 9px;
        background: white;
        box-shadow: 2px 0 0 white, 4px 0 0 white, 4px -2px 0 white, 4px -4px 0 white, 4px -6px 0 white, 4px -8px 0 white;
        transform: rotate(45deg);
    }

    .form-inner input[type="submit"] {
        background: #1762EE;
    }
</style>

templates/services.html
{% include 'header.html' %}

<div class="container mt-5">
    <h2>Список заказов:</h2>
    <table class="table">
        <thead>
        <tr>
            <th>Название</th>
            <th>Цена</th>
            <th>Дедлайн</th>
        </tr>
        </thead>
        <tbody>
        {% for i in services %}
        <tr>
            <td>{{ i.title }}</td>
            <td>{{ i.prepaid_expense }}</td>
            <td>{{ i.dead_line }}</td>
            <td>
                <button type="button" class="btn btn-success">
                    <a href="/services_list/{{i.id}}/update/">Изменить</a>
                </button>
                <button type="button" class="btn btn-danger">
                    <a href="/services_list/{{i.id}}/delete/">Удалить</a>
                </button>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>

<style>
    a{
        text-decoration: none;
        font-weight: bolder;
        color: white;
    }
</style>

<br><br><br><br><br><br><br><br><br>
{% include 'footer.html' %}

templates/update_service.html
{% load static %}
{% include 'header.html' %}
<link rel="stylesheet" href="{% static 'css/create_service.css' %}">
<form class="decor"  method="POST" enctype="multipart/form-data">
    <div class="form-left-decoration"></div>
    <div class="form-right-decoration"></div>
    <div class="circle"></div>
    <div class="form-inner">
        <h3>Изменить</h3>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Отправить">
        <input type="reset" value="Очистить">
    </div>
</form>
{% include 'footer.html' %}

templates/user_list.html
<h1>Ура у тебя получилось</h1>


<form action="{% url 'persons:logout' %}" method="POST">
    {% csrf_token %}
    <button type="submit">Выйти из аккаунта</button>
</form>